chore: bump cw-dex-astroport version
apollodao/cw-dex-router pull request #36
Opened 2024-05-06 00:05 UTC by ApolloGie

2024-05-06 08:34 UTC, apollo-sturdy requested changes

2024-05-06 08:34 UTC, apollo-sturdy commented on CHANGELOG.md
> +- Replace `cw-dex/astroport` with `cw-dex-astroport`.
Incorrect version and date

2024-05-06 08:34 UTC, apollo-sturdy commented on Cargo.toml
> +cw-dex-astroport  = { version = "0.2.0-rc.1", optional = true}
You'll also have to stop using Pool enum from `cw-dex` on https://github.com/apollodao/cw-dex-router/blob/master/src/operations.rs#L7

and create your own pool enum with variants based on feature flags in this crate.

2024-08-28 11:56 UTC, pacmanifold requested changes

2024-08-28 11:56 UTC, pacmanifold commented on Makefile.toml
> +RUST_VERSION = "1.75.0"
lets run 1.79.0. for some reason 1.75 takes 30 min for me to compile the latest osmosis-std (after they upgraded go version to 1.23)

2024-08-28 11:56 UTC, pacmanifold commented on Makefile.toml
> +RUST_VERSION = "1.75.0"
```suggestion
RUST_VERSION = "1.79.0"
```

2024-08-28 11:56 UTC, pacmanifold commented on Makefile.toml
> +NIGHTLY_VERSION = "nightly-2023-08-29"
why downgrade to older nightly?

2024-08-28 11:56 UTC, pacmanifold commented on Cargo.toml
> +cw-dex = "0.6.0-rc.5"
remove rc

2024-08-28 12:26 UTC, pacmanifold approved these changes

2024-08-28 12:27 UTC, merged